### ISSUE TITLE
Update README for this fork

### ISSUE THREAD

**Issue by aramperes** [GlowstonePlusPlus/network#2]
The README file should reflect that this is Glowstone's fork of the original flow-network library.

Donation links should be removed, credits updated, description updated. Instructions about building with Gradle should be removed.

The instructions to use this library in a Maven project (instead of a Gradle project) should be:

 - Maven dependency:
   ```
   <dependency>
     <groupId>com.flowpowered</groupId>
     <artifactId>flow-network</artifactId>
     <version>1.2.4</version>
   </dependency>
   ```

  - Maven repository:
    ```
    <repository>
      <id>glowstone-repo</id>
      <url>https://repo.glowstone.net/content/repositories/snapshots/</url>
    </repository>
    ```

There are currently no hosted Javadocs for this fork.

The CI badge should point to https://circleci.com/gh/GlowstoneMC/network

Add a link to our Discord: https://discord.gg/TFJqhsC

**Comment by preeti98** [comment]
May I please work on this issue?

**Comment by aramperes** [comment]
@preeti98 sure thing!
